service: backend
runtime: nodejs20
env: standard
entrypoint: node server.js

env_variables:
  PORT: "8080"
  TICKETMASTER_API_KEY: "XPJl0WGHMTPqdaR81cLGOJfDNhAn8bsG"
  IPINFO_TOKEN: "c8838bbdab221d"
  GOOGLE_GEOCODING_KEY: "AIzaSyC-r6qxtxEbZsjYmdvqI9fYmpd4cLyp22A"

  # --- Spotify credentials ---
  SPOTIFY_CLIENT_ID: "d538590727064e68ab0f0bd98402455c"
  SPOTIFY_CLIENT_SECRET: "41b79599a1264311951ce5320c1927ad"

  # --- MongoDB ---
  MONGO_URI: "mongodb+srv://ramyasrivasamsetty_db_user:1Sv53l8h7SrVwg9A@events-app.ubeuirn.mongodb.net/eventsdb?retryWrites=true&w=majority"
  DB_NAME: "eventsdb"
  COLLECTION: "favorites"

automatic_scaling:
  max_instances: 1
